name: "Rate Joke Action"
description: "Rates a joke using the Gemini API"

inputs:
  joke:
    description: "The joke to be rated"
    required: true
  token:
    description: "Gemini API key to use for the request"
    default: ${{ github.token }}

outputs:
  result:
    description: "AI-generated joke evaluation"

runs:
  using: node24
  main: dist/index.js